#set(CTEST_SOURCE_DIRECTORY "/home/behnam/workspace/gtest_gmock/tests/src")
set(CTEST_BINARY_DIRECTORY "/home/behnam/workspace/gtest_gmock/build/tests")
set(ENV{CXXFLAGS "--coverage"})
set(CTEST_CMAKE_GENERATOR "Ninja")
set(CTEST_USE_LAUNCHERS 1)
set(CTEST_COVERAGE_COMMAND "gcov")
set(CTEST_MEMORYCHECK_COMMAND "valgrind")

ctest_start("Continuous")
ctest_configure()
ctest_build()
ctest_test()
ctest_coverage()
ctest_memcheck()
ctest_submit()
